# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

    config.vm.box = "almalinux/8"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"


    config.vm.define "server" do |server|
      server.vm.hostname = "server.loc"
      server.vm.network "private_network", ip: "192.168.56.10"
    end
 
   config.vm.define "client" do |client|
      client.vm.hostname = "client.loc"
      client.vm.network "private_network", ip: "192.168.56.20"
    end

   config.vm.define "ras" do |ras|
      ras.vm.hostname = "ras.loc"
      ras.vm.network "private_network", ip: "192.168.56.30"
    end


  
    config.vm.provision "base", type: "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "ansible/playbook-base.yml"
        ansible.become = "true"
    end    
    
    config.vm.provision "openvpn", type: "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "ansible/playbook-openvpn.yml"
        ansible.become = "true"
    end


    config.vm.provision "rasvpn", type: "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "ansible/playbook-ras.yml"
        ansible.become = "true"
    end

  end
   
