# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :backup => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.160'
  },
  :client => {
    :box_name => "centos/7",
    :ip_addr => '192.168.11.150'
  }
}

Vagrant.configure("2") do |config|

 MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]

      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]


       if boxname == :backup
          # Добавление дополнительного диска к серверу "backup"
          vb.customize ['storagectl', :id, '--name', 'SATA', '--add', 'sata']
          vb.customize ['createhd', '--filename', 'var-backup.vdi', '--size', '2048']
          vb.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'var-backup.vdi']
        end
      end 
     end
    end

   config.vbguest.auto_update = false
   config.vbguest.no_remote = true


   config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "./provision.yml"
        ansible.force_remote_user = "vagrant"
        ansible.become = "true"
        ansible.inventory_path = "./hosts"
      end
end
