Vagrant.configure("2") do |config|
    config.vm.box = "almalinux/9"
 
    config.vm.provider :virtualbox do |v|
       v.memory = 2048
       v.cpus = 1
    end

    config.vm.provision "ansible" do |ansible|
       ansible.playbook = "ansible/provision.yml"
       ansible.become = "true"    
       ansible.verbose = "v"
    end

    config.vm.define "ipaserver" do |server|
        server.vm.host_name = 'ipaserver.otus.lan'
        server.vm.network :private_network, ip: "192.168.57.10"
        server.vm.network "forwarded_port", guest: 80, host: 8080
        server.vm.network "forwarded_port", guest: 443, host: 443
    end


    config.vm.define "ipaclient" do |client|
        client.vm.host_name = 'ipaclient.otus.lan'
        client.vm.network :private_network, ip: "192.168.57.11"
    end    
  
end
