# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "nfsserver" do |nfsserver|
    nfsserver.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    nfsserver.vm.hostname = "nfsserver"
  end

  config.vm.define "nfsclient" do |nfsclient|
    nfsclient.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
    nfsclient.vm.hostname = "nfsclient"
  end

end
