---
- name: YML inetRouter
  hosts: all
  become: true
  vars:
    ansible_verbosity: 2

  tasks:
    - name: install iptables service
      yum:
        name:
          - iptables
          - iptables-services
          - mc
        state: present
        update_cache: true

    - name: copy iptables config to InetRouter
      template:
        src: inetRouter/internetRouter.iptables.conf.j2
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: 0600

    - name: add routes
      template:
        src: "inetRouter/{{  item  }}"
        dest: /etc/sysconfig/network-scripts/
      loop:
        - route-eth1
      notify:
        - restart network

    - name: start and enable iptables service
      service:
        name: iptables
        state: restarted
        enabled: true

    - name: Restart network command
      command: systemctl restart network

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
