---
- name: Otus ALL Playbook
  hosts: all
  become: true
  vars:
    ansible_verbosity: 2

  tasks:
    - name: Install traceroute
      yum:
        name: traceroute
        state: present

    - name: Set up forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: "1"
        state: present
      when: (ansible_hostname == "centralRouter") or
        (ansible_hostname == "inetRouter")   or
        (ansible_hostname == "office1Router")   or
        (ansible_hostname == "office2Router")
      notify: restart network

    - name: Disable default route
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: DEFROUTE=no
      when: (ansible_hostname == "centralRouter") or
        (ansible_hostname == "centralServer") or
        (ansible_hostname == "office1Router")  or
        (ansible_hostname == "office1Server") or
        (ansible_hostname == "office2Router")  or
        (ansible_hostname == "office2Server")
      notify: restart network

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
