---
  - name: NGINX | Install and conf NGINX
    hosts: web
    become: true
    tasks:
      - name: NGINX | Install EPEL Repo package
        yum:
          name: epel-release
          state: present

      - name: NGINX | Install NGINX package
        yum:
          name: nginx
          state: latest
        notify:
          - restart nginx

#      - name: copy nginx conf
#        copy:
#          src: conf/nginx.conf
#          dest: /etc/nginx/nginx.conf
#        notify:
#          - restart nginx

#      - name: enable audit /etc/nginx/nginx.conf
#        copy: 
#          content: -a exit,always -F path=/etc/nginx/nginx.conf -F perm=wa
#          dest: /etc/audit/rules.d/nginx.rules

#      - name: edit /etc/audisp/plugins.d/syslog.conf
#        lineinfile:
#          regexp: "^active = no"
#          line: "active = yes"
#          path: /etc/audisp/plugins.d/syslog.conf
#        notify: restart auditd

      - name: reboot web
        reboot:

    handlers:
      - name: restart nginx
        systemd:
          name: nginx
          state: restarted
          enabled: yes

      - name: restart rsyslog
        systemd:
          name: rsyslog
          state: restarted
          enabled: yes



  - name: Rsyslog
    hosts: log
    become: true
    tasks:
      - name: Update Rsyslog
        apt:
          name: rsyslog
          state: latest


  - name: Configuration rsyslog server
    hosts: log
    become: true
    tasks:
      - name: edit /etc/rsyslog.conf add ModLoad imtcp
        lineinfile: 
          path: /etc/rsyslog.conf
          regexp: '^#\$ModLoad imtcp'
          line: "$ModLoad imtcp"
          state: present

      - name: edit /etc/rsyslog.conf
        lineinfile: 
          path: /etc/rsyslog.conf
          regexp: '^#\$ModLoad imudp'
          line: "$ModLoad imudp"
          state: present

      - name: edit /etc/rsyslog.conf add InputTCPServerRun 514
        lineinfile: 
          path: /etc/rsyslog.conf
          regexp: '^#\$InputTCPServerRun 514'
          line: "$InputTCPServerRun 514"
          state: present

      - name: edit /etc/rsyslog.conf add UDPServerRun 514
        lineinfile: 
          path: /etc/rsyslog.conf
          regexp: '^#\$UDPServerRun 514'
          line: "$UDPServerRun 514"
          state: present
        notify: restart rsyslog

      - name: edit /etc/rsyslog.conf
        blockinfile:
          dest: /etc/rsyslog.conf
          insertbefore: "#### GLOBAL DIRECTIVES ####"
          block: |
            $template remote-incoming-logs,"/var/log/%HOSTNAME%.log"
            *.* ?remote-incoming-logs
            & stop
      notify: restart rsyslog


    handlers:
      - name: Restart Rsyslog
        service:
          name: rsyslog
          state: restarted
