# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "bash" do |bash|
    bash.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    bash.vm.hostname = "bash"
    bash.vm.provision "file", source: "./access.log", destination: "/tmp/access.log"
    bash.vm.provision "file", source: "./script2.sh", destination: "/tmp/script.sh"
    bash.vm.provision "shell", inline: "(echo \"0 * * * * /tmp/script.sh \") >> /var/spool/cron/root"
    bash.vm.provision "shell", inline: <<-SHELL
               mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
               yum install mailx -y
               chmod +x /tmp/script.sh
            SHELL
  end
end
