# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "2004.01"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end

  config.vm.define "systemd" do |bash|
    bash.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    bash.vm.hostname = "bash"
    bash.vm.provision "shell", inline: <<-SHELL
               yum update -y && yum install nginx -y
            SHELL
#    bash.vm.provision "shell", path: "script.sh"
  end
end
