---
- name: YML centralRouter
  hosts: all
  become: true
  vars:
    ansible_verbosity: 2

  tasks:

    - name: Install nmap
      yum:
        name: 
          - nmap
        state: latest

    - name: Create .ssh directory
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'

    - name: Copy public key to centralRouter
      copy:
        src: key/id_rsa.pub
        dest: /root/.ssh/id_rsa.pub
        owner: root
        group: root
        mode: 0755
        force: yes

    - name: Copy private key to CentralRouter
      copy:
        src: key/id_rsa
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: 0600
        force: yes

    - name: Create known_hosts
      shell: ssh-keyscan -H 192.168.255.1 >> ~/.ssh/known_hosts

    - name: Copy knock.sh
      template:
        src: centralRouter/knock.sh.j2
        dest: /root/knock.sh
        mode: '0777'

    - name: add default gateway for centralRouter
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.255.1
      notify:
        - restart network

    - name: add routes
      template:
        src: "centralRouter/{{  item  }}"
        dest: /etc/sysconfig/network-scripts/
      loop:
        - route-eth1
        - route-eth5
        - route-eth6
      notify:
        - restart network

    - name: Restart network command
      command: systemctl restart network


  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
