---
- name: YML centralServer
  hosts: all
  become: true
  vars:
    ansible_verbosity: 2

  tasks:
    - name: add default gateway for centralRouter
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.0.1
      notify:
        - restart network

    - name: add routes
      template:
        src: "centralServer/{{  item  }}"
        dest: /etc/sysconfig/network-scripts/
      loop:
        - route-eth1

    - name: Restart network command
      command: systemctl restart network

    - name: nginx restart
      service:
        name: nginx
        state: restarted
        enabled: true

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
