---
- name: YML inetRouter2
  hosts: all
  become: true
  vars:
    ansible_verbosity: 2

  tasks:
    - name: install iptables service
      yum:
        name:
          - iptables
          - iptables-services
        state: present
        update_cache: true

    - name: add default gateway for centralRouter
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.255.22
      notify:
        - restart network

    - name: Configure PREROUTING
      command: iptables -t nat -A PREROUTING -p tcp -i eth2 --dport 8080 -j DNAT --to-destination 192.168.0.2:80
      ignore_errors: true


    - name: Configure POSTROUTING
      command: iptables -t nat -A POSTROUTING -s 192.168.50.0/24 -d 192.168.0.2 -j MASQUERADE
      ignore_errors: true

    - name: Restart network command
      command: systemctl restart network

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted

    - name: iptables save
      command: service iptables save

    - name: iptables restart
      service:
        name: iptables
        state: restarted
        enabled: true
