---
- name: YML office2Router
  hosts: all
  become: true
  vars:
    ansible_verbosity: 2

  tasks:
    - name: Add default gateway for centralRouter
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.255.5
      notify:
        - restart network

    - name: Add routes
      template:
        src: "office2Router/{{  item  }}"
        dest: /etc/sysconfig/network-scripts/
      loop:
        - route-eth1
      notify:
        - restart network

    - name: Restart network command
      command: systemctl restart network

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
