Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.10.10"
    web.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL
  end


  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "./ansible/provision-web.yml"
    ansible.force_remote_user = "vagrant"
    ansible.become = "true"
    ansible.inventory_path = "./ansible/hosts"
  end


  config.vm.define "log" do |log|
    log.vm.box = "centos/7"
    log.vm.hostname = "log"
    log.vm.network "private_network", ip: "192.168.10.20"
    log.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            systemctl restart sshd
          SHELL
  end


  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "./ansible/provision-log.yml"
    ansible.force_remote_user = "vagrant"
    ansible.become = "true"
    ansible.inventory_path = "./ansible/hosts"
  end


end
